
apiVersion: extensions/v1beta1

kind: Ingress

metadata:

  name: starbucks-api-jants

  annotations:

    kubernetes.io/ingress.class: kong

spec:

  rules:

  - http:

      paths:

      - path: /admin

        backend:

          serviceName: spring-starbucks-api-service

          servicePort: 81
